name: MCLegacy
version: 1.0
author: moderator_man
main: net.mclegacy.plugin.MCLegacy
softdepend: [ dynmap ]
loadbefore: [ dynmap ]
commands:
  ban:
    description: Issue a global permanent global ban.
    usage: /ban <username> (reason)
    permission: mclegacy.ban
  tempban:
    description: Issue a temporary global ban.
    usage: /tempban <username> <duration> (reason)
    permission: mclegacy.tempban
  unban:
    description: Pardon a global ban.
    usage: /unban <username>
    permission: mclegacy.unban
  link:
    description: Link your Minecraft account to your MCLegacy account.
    usage: /link <code>
dependencies:
  - com.auth0:java-jwt:4.2.1
  - com.fasterxml.jackson.core:jackson-annotations:2.13.4
  - com.fasterxml.jackson.core:jackson-core:2.13.4
  - com.fasterxml.jackson.core:jackson-databind:2.13.4.2
  - com.squareup.okhttp3:okhttp-jvm:5.0.0-alpha.11
  - com.squareup.okio:okio-jvm:3.2.0
  - commons-cli:commons-cli:1.5.0
  - javax.servlet:javax.servlet-api:3.1.0
  - org.eclipse.jetty.websocket:websocket-api:9.4.50.v20221201
  - org.eclipse.jetty.websocket:websocket-client:9.4.50.v20221201
  - org.eclipse.jetty.websocket:websocket-common:9.4.50.v20221201
  - org.eclipse.jetty.websocket:websocket-server:9.4.50.v20221201
  - org.eclipse.jetty.websocket:websocket-servlet:9.4.50.v20221201
  - org.eclipse.jetty:jetty-client:9.4.50.v20221201
  - org.eclipse.jetty:jetty-http:9.4.50.v20221201
  - org.eclipse.jetty:jetty-io:9.4.50.v20221201
  - org.eclipse.jetty:jetty-security:9.4.50.v20221201
  - org.eclipse.jetty:jetty-server:9.4.50.v20221201
  - org.eclipse.jetty:jetty-servlet:9.4.50.v20221201
  - org.eclipse.jetty:jetty-util-ajax:9.4.50.v20221201
  - org.eclipse.jetty:jetty-util:9.4.50.v20221201
  - org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10
  - org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.20
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.20
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.10
  - org.jetbrains:annotations:13.0